export default {
  'post-tool-search': 'POST /search',
  'post-tool-get': 'POST /get',
  'post-tool-create': 'POST /create',
  'post-tool-update': 'POST /update',
  'post-tool-duplicate': 'POST /duplicate',
  'post-tool-delete': 'POST /delete',
  'patch-tool-draft': 'PATCH /draft',
  'post-tool-drafts': 'POST /drafts',
  'post-tool-export': 'POST /export',
  'post-tool-generate': 'POST /generate',
  'post-tool-generations': 'POST /generations',
  'post-tool-csv': 'POST /csv',
  'post-tool-context': 'POST /context',
  'post-tool-group': 'POST /group',
  'post-tool-problem': 'POST /problem',
  'post-tool-refresh': 'POST /refresh',
  'types': 'Types',
}
