export default {
  'post-tool-title': 'POST /title',
  'post-tool-search': 'POST /search',
  'post-tool-get': 'POST /get',
  'post-tool-create': 'POST /create',
  'post-tool-update': 'POST /update',
  'post-tool-duplicate': 'POST /duplicate',
  'post-tool-delete': 'POST /delete',
  'post-tool-draft': 'POST /draft',
  'post-tool-drafts': 'POST /drafts',
  'post-tool-export': 'POST /export',
  'post-tool-generate': 'POST /generate',
  'post-tool-generations': 'POST /generations',
  'post-tool-csv': 'POST /csv',
  'post-tool-context': 'POST /context',
  'post-tool-group': 'POST /group',
  'post-tool-preview': 'POST /preview',
  'post-tool-problem': 'POST /problem',
  'post-tool-refresh': 'POST /refresh',
  'get-tool-watch': 'GET /watch',
  'post-tool-watch': 'POST /watch',
  'post-tool-text-download': 'POST /text_download',
  'post-tool-file-download': 'POST /file_download',
  'post-tool-call-download': 'POST /call_download',
  'types': 'Types',
}
