export default {
  'post-simulation-title': 'POST /title',
  'post-simulation-get': 'POST /get',
  'post-simulation-search': 'POST /search',
  'post-simulation-create': 'POST /create',
  'post-simulation-context': 'POST /context',
  'post-simulation-csv': 'POST /csv',
  'post-simulation-update': 'POST /update',
  'post-simulation-duplicate': 'POST /duplicate',
  'post-simulation-delete': 'POST /delete',
  'post-simulation-draft': 'POST /draft',
  'post-simulation-drafts': 'POST /drafts',
  'post-simulation-export': 'POST /export',
  'post-simulation-generate': 'POST /generate',
  'post-simulation-generations': 'POST /generations',
  'post-simulation-problem': 'POST /problem',
  'post-simulation-refresh': 'POST /refresh',
  'post-simulation-group': 'POST /group',
  'get-simulation-watch': 'GET /watch',
  'post-simulation-text-download': 'POST /text_download',
  'post-simulation-file-download': 'POST /file_download',
  'post-simulation-call-download': 'POST /call_download',
  'types': 'Types',
}
