export default {
  'post-simulation-get': 'POST /get',
  'post-simulation-search': 'POST /search',
  'post-simulation-create': 'POST /create',
  'post-simulation-context': 'POST /context',
  'post-simulation-csv': 'POST /csv',
  'post-simulation-update': 'POST /update',
  'post-simulation-duplicate': 'POST /duplicate',
  'post-simulation-delete': 'POST /delete',
  'patch-simulation-draft': 'PATCH /draft',
  'post-simulation-drafts': 'POST /drafts',
  'post-simulation-export': 'POST /export',
  'post-simulation-generate': 'POST /generate',
  'post-simulation-generations': 'POST /generations',
  'post-simulation-problem': 'POST /problem',
  'post-simulation-refresh': 'POST /refresh',
  'post-simulation-group': 'POST /group',
  'types': 'Types',
}
