export default {
  'activity': 'glow system activity',
  'audio_download': 'glow system audio_download',
  'call_download': 'glow system call_download',
  'context': 'glow system context',
  'export': 'glow system export',
  'file_download': 'glow system file_download',
  'file_preview': 'glow system file_preview',
  'generate': 'glow system generate',
  'generations': 'glow system generations',
  'group': 'glow system group',
  'groups': 'glow system groups',
  'health': 'glow system health',
  'image_download': 'glow system image_download',
  'pricing': 'glow system pricing',
  'problem': 'glow system problem',
  'refresh': 'glow system refresh',
  'resolve': 'glow system resolve',
  'session': 'glow system session',
  'sessions': 'glow system sessions',
  'text_download': 'glow system text_download',
  'title': 'glow system title',
  'video_download': 'glow system video_download',
  'watch': 'glow system watch',
}
