export default {
  'context': 'glow system context',
  'export': 'glow system export',
  'generate': 'glow system generate',
  'generations': 'glow system generations',
  'group': 'Group',
  'problem': 'glow system problem',
  'refresh': 'glow system refresh',
  'resolve': 'glow system resolve',
  'title': 'glow system title',
  'watch': 'glow system watch',
  'activity': 'Activity',
  'health': 'Health',
  'pricing': 'Pricing',
  'session': 'Session',
}
