export default {
  'post-attempt-get': 'POST /get',
  'post-attempt-join': 'POST /join',
  'post-attempt-leave': 'POST /leave',
  'post-attempt-archive': 'POST /archive',
  'post-attempt-refresh': 'POST /refresh',
  'post-attempt-docs': 'POST /docs',
  'post-attempt-export': 'POST /export',
  'post-attempt-start': 'POST /start',
  'post-attempt-next': 'POST /next',
  'post-attempt-end': 'POST /end',
  'post-attempt-end-all': 'POST /end-all',
  'post-attempt-expire': 'POST /expire',
  'post-attempt-message': 'POST /message',
  'post-attempt-grade': 'POST /grade',
  'post-attempt-stop': 'POST /stop',
  'post-attempt-response': 'POST /response',
  'post-attempt-use-previous': 'POST /use-previous',
  'post-attempt-audio-start': 'POST /audio/start',
  'post-attempt-audio-frame': 'POST /audio/frame',
  'post-attempt-audio-stop': 'POST /audio/stop',
  'post-attempt-audio-mute': 'POST /audio/mute',
  'post-attempt-search': 'POST /search',
  'get-attempt-download-upload-id': 'GET /download/{upload_id}',
  'types': 'Types',
}
