export default {
  'call_download': 'glow fields call_download',
  'context': 'glow fields context',
  'create': 'glow fields create',
  'csv': 'glow fields csv',
  'delete': 'glow fields delete',
  'draft': 'glow fields draft',
  'drafts': 'glow fields drafts',
  'duplicate': 'glow fields duplicate',
  'export': 'glow fields export',
  'file_download': 'glow fields file_download',
  'generate': 'glow fields generate',
  'generations': 'glow fields generations',
  'get': 'glow fields get',
  'group': 'glow fields group',
  'problem': 'glow fields problem',
  'refresh': 'glow fields refresh',
  'search': 'glow fields search',
  'text_download': 'glow fields text_download',
  'title': 'glow fields title',
  'update': 'glow fields update',
  'watch': 'glow fields watch',
}
