export default {
  'post-document-title': 'POST /title',
  'post-document-search': 'POST /search',
  'post-document-get': 'POST /get',
  'post-document-create': 'POST /create',
  'post-document-update': 'POST /update',
  'post-document-duplicate': 'POST /duplicate',
  'post-document-delete': 'POST /delete',
  'post-document-draft': 'POST /draft',
  'post-document-drafts': 'POST /drafts',
  'post-document-context': 'POST /context',
  'post-document-generate': 'POST /generate',
  'post-document-generations': 'POST /generations',
  'post-document-group': 'POST /group',
  'post-document-problem': 'POST /problem',
  'post-document-refresh': 'POST /refresh',
  'post-document-export': 'POST /export',
  'post-document-csv': 'POST /csv',
  'get-document-watch': 'GET /watch',
  'post-document-text-download': 'POST /text_download',
  'post-document-text-upload': 'POST /text_upload',
  'post-document-file-download': 'POST /file_download',
  'post-document-file-preview': 'POST /file_preview',
  'post-document-file-upload': 'POST /file_upload',
  'post-document-call-download': 'POST /call_download',
  'types': 'Types',
}
