export default {
  'post-document-search': 'POST /search',
  'post-document-get': 'POST /get',
  'post-document-create': 'POST /create',
  'post-document-update': 'POST /update',
  'post-document-duplicate': 'POST /duplicate',
  'post-document-delete': 'POST /delete',
  'patch-document-draft': 'PATCH /draft',
  'post-document-drafts': 'POST /drafts',
  'post-document-context': 'POST /context',
  'post-document-generate': 'POST /generate',
  'post-document-generations': 'POST /generations',
  'post-document-group': 'POST /group',
  'post-document-problem': 'POST /problem',
  'post-document-refresh': 'POST /refresh',
  'post-document-export': 'POST /export',
  'post-document-csv': 'POST /csv',
  'post-document-text-upload': 'POST /text/upload',
  'post-document-text-download': 'POST /text/download',
  'post-document-file-upload': 'POST /file/upload',
  'post-document-file-download': 'POST /file/download',
  'post-document-file-preview': 'POST /file/preview',
  'types': 'Types',
}
