export default {
  'context': 'glow agents context',
  'create': 'glow agents create',
  'csv': 'glow agents csv',
  'delete': 'glow agents delete',
  'draft': 'glow agents draft',
  'drafts': 'glow agents drafts',
  'duplicate': 'glow agents duplicate',
  'export': 'glow agents export',
  'generate': 'glow agents generate',
  'generations': 'glow agents generations',
  'get': 'glow agents get',
  'group': 'glow agents group',
  'problem': 'glow agents problem',
  'refresh': 'glow agents refresh',
  'search': 'glow agents search',
  'title': 'glow agents title',
  'update': 'glow agents update',
  'watch': 'glow agents watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
