export default {
  'login': 'glow login',
  'logout': 'glow logout',
  'mcp': 'Mcp',
  'init': 'glow init',
  'logs': 'glow logs',
  'deploy': 'glow deploy',
  'redeploy': 'glow redeploy',
  'stop': 'glow stop',
  'start': 'glow start',
  'destroy': 'glow destroy',
  'status': 'glow status',
  'backup': 'Backup',
  'personas': 'Personas',
  'scenarios': 'Scenarios',
  'simulations': 'Simulations',
  'documents': 'Documents',
  'agents': 'Agents',
  'models': 'Models',
  'providers': 'Providers',
  'parameters': 'Parameters',
  'fields': 'Fields',
  'tools': 'Tools',
  'departments': 'Departments',
  'cohorts': 'Cohorts',
  'evals': 'Evals',
  'rubrics': 'Rubrics',
  'profiles': 'Profiles',
  'auths': 'Auths',
  'settings': 'Settings',
  'attempts': 'Attempts',
  'tests': 'Tests',
  'system': 'System',
}
