export default {
  'login': 'glow login',
  'logout': 'glow logout',
  'health': 'glow health',
  'context': 'glow context',
  'emulate': 'glow emulate',
  'unemulate': 'glow unemulate',
  'generate': 'glow generate',
  'stream': 'glow stream',
  'instances': 'Instances',
  'use': 'glow use',
  'ledger': 'Ledger',
  'admin': 'Admin',
  'personas': 'Personas',
  'scenarios': 'Scenarios',
  'simulations': 'Simulations',
  'documents': 'Documents',
  'agents': 'Agents',
  'models': 'Models',
  'providers': 'Providers',
  'parameters': 'Parameters',
  'fields': 'Fields',
  'tools': 'Tools',
  'departments': 'Departments',
  'cohorts': 'Cohorts',
  'evals': 'Evals',
  'rubrics': 'Rubrics',
  'benchmarks': 'Benchmarks',
  'profiles': 'Profiles',
  'auths': 'Auths',
  'settings': 'Settings',
  'attempt': 'Attempt',
  'test': 'Test',
  'chat': 'Chat',
  'activity': 'Activity',
  'record': 'Record',
  'dashboard': 'Dashboard',
  'leaderboard': 'Leaderboard',
  'reports': 'Reports',
  'home': 'Home',
  'practice': 'Practice',
  'group': 'Group',
  'pricing': 'Pricing',
  'session': 'Session',
  'invocation': 'Invocation',
}
