export default {
  'agent': 'Agent',
  'attempt': 'Attempt',
  'auth': 'Auth',
  'cohort': 'Cohort',
  'department': 'Department',
  'document': 'Document',
  'eval': 'Eval',
  'field': 'Field',
  'model': 'Model',
  'parameter': 'Parameter',
  'persona': 'Persona',
  'profile': 'Profile',
  'provider': 'Provider',
  'rubric': 'Rubric',
  'scenario': 'Scenario',
  'setting': 'Setting',
  'simulation': 'Simulation',
  'system': 'System',
  'test': 'Test',
  'tool': 'Tool',
}
