export default {
  'activity': 'Activity',
  'agents': 'Agents',
  'attempt': 'Attempt',
  'auths': 'Auths',
  'benchmark': 'Benchmark',
  'chat': 'Chat',
  'cohorts': 'Cohorts',
  'dashboard': 'Dashboard',
  'departments': 'Departments',
  'docs-proxy': 'Docs Proxy',
  'documents': 'Documents',
  'evals': 'Evals',
  'fields': 'Fields',
  'group': 'Group',
  'health': 'Health',
  'home': 'Home',
  'leaderboard': 'Leaderboard',
  'models': 'Models',
  'parameters': 'Parameters',
  'personas': 'Personas',
  'practice': 'Practice',
  'pricing': 'Pricing',
  'profiles': 'Profiles',
  'providers': 'Providers',
  'record': 'Record',
  'reports': 'Reports',
  'rubrics': 'Rubrics',
  'scenarios': 'Scenarios',
  'session': 'Session',
  'settings': 'Settings',
  'simulations': 'Simulations',
  'stream': 'Stream',
  'test': 'Test',
  'tools': 'Tools',
}
