export default {
  'root': 'GET /',
  'well-known-oauth-authorization-server': 'GET /.well-known/oauth-authorization-server',
  'well-known-openid-configuration': 'GET /.well-known/openid-configuration',
  'auth-client-config': 'GET /auth/client-config',
  'authorize': 'GET /authorize',
  'callback': 'GET /callback',
  'jwks': 'GET /jwks',
  'login': 'GET /login',
  'logout': 'GET /logout',
  'me': 'GET /me',
  'oidc-callback': 'GET /oidc-callback',
  'token': 'POST /token',
  'userinfo': 'GET /userinfo',
  'agent': 'Agent',
  'attempt': 'Attempt',
  'auth': 'Auth',
  'cohort': 'Cohort',
  'department': 'Department',
  'document': 'Document',
  'eval': 'Eval',
  'field': 'Field',
  'model': 'Model',
  'parameter': 'Parameter',
  'persona': 'Persona',
  'profile': 'Profile',
  'provider': 'Provider',
  'rubric': 'Rubric',
  'scenario': 'Scenario',
  'setting': 'Setting',
  'simulation': 'Simulation',
  'system': 'System',
  'test': 'Test',
  'tool': 'Tool',
}
