export default {
  'post-scenario-get': 'POST /get',
  'post-scenario-search': 'POST /search',
  'post-scenario-create': 'POST /create',
  'post-scenario-csv': 'POST /csv',
  'post-scenario-update': 'POST /update',
  'post-scenario-duplicate': 'POST /duplicate',
  'post-scenario-delete': 'POST /delete',
  'patch-scenario-draft': 'PATCH /draft',
  'post-scenario-drafts': 'POST /drafts',
  'post-scenario-export': 'POST /export',
  'post-scenario-generate': 'POST /generate',
  'post-scenario-generations': 'POST /generations',
  'post-scenario-context': 'POST /context',
  'post-scenario-group': 'POST /group',
  'post-scenario-problem': 'POST /problem',
  'post-scenario-refresh': 'POST /refresh',
  'post-scenario-image-upload': 'POST /image/upload',
  'post-scenario-image-download': 'POST /image/download',
  'post-scenario-video-upload': 'POST /video/upload',
  'post-scenario-video-download': 'POST /video/download',
  'post-scenario-text-download': 'POST /text/download',
  'post-scenario-file-download': 'POST /file/download',
  'post-scenario-file-preview': 'POST /file/preview',
  'types': 'Types',
}
