export default {
  'context': 'glow parameters context',
  'create': 'glow parameters create',
  'csv': 'glow parameters csv',
  'delete': 'glow parameters delete',
  'draft': 'glow parameters draft',
  'drafts': 'glow parameters drafts',
  'duplicate': 'glow parameters duplicate',
  'export': 'glow parameters export',
  'generate': 'glow parameters generate',
  'generations': 'glow parameters generations',
  'get': 'glow parameters get',
  'group': 'glow parameters group',
  'problem': 'glow parameters problem',
  'refresh': 'glow parameters refresh',
  'search': 'glow parameters search',
  'title': 'glow parameters title',
  'update': 'glow parameters update',
  'watch': 'glow parameters watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
