export default {
  'archive': 'glow attempts archive',
  'complete': 'glow attempts complete',
  'context': 'glow attempts context',
  'draft': 'glow attempts draft',
  'drafts': 'glow attempts drafts',
  'export': 'glow attempts export',
  'generate': 'glow attempts generate',
  'generations': 'glow attempts generations',
  'get': 'glow attempts get',
  'group': 'glow attempts group',
  'problem': 'glow attempts problem',
  'refresh': 'glow attempts refresh',
  'search': 'glow attempts search',
  'start': 'glow attempts start',
  'stop': 'glow attempts stop',
  'title': 'glow attempts title',
  'watch': 'glow attempts watch',
  'audio': 'Audio',
  'call': 'Call',
  'file': 'File',
  'image': 'Image',
  'text': 'Text',
  'video': 'Video',
  'chat': 'Chat',
  'dashboard': 'Dashboard',
  'home': 'Home',
  'leaderboard': 'Leaderboard',
  'practice': 'Practice',
}
