export default {
  'context': 'glow settings context',
  'create': 'glow settings create',
  'csv': 'glow settings csv',
  'decrypt': 'glow settings decrypt',
  'delete': 'glow settings delete',
  'draft': 'glow settings draft',
  'drafts': 'glow settings drafts',
  'duplicate': 'glow settings duplicate',
  'export': 'glow settings export',
  'generate': 'glow settings generate',
  'generations': 'glow settings generations',
  'get': 'glow settings get',
  'group': 'glow settings group',
  'problem': 'glow settings problem',
  'refresh': 'glow settings refresh',
  'search': 'glow settings search',
  'title': 'glow settings title',
  'update': 'glow settings update',
  'watch': 'glow settings watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
