export default {
  'post-persona-title': 'POST /title',
  'post-persona-get': 'POST /get',
  'post-persona-search': 'POST /search',
  'post-persona-create': 'POST /create',
  'post-persona-csv': 'POST /csv',
  'post-persona-update': 'POST /update',
  'post-persona-duplicate': 'POST /duplicate',
  'post-persona-delete': 'POST /delete',
  'post-persona-draft': 'POST /draft',
  'post-persona-drafts': 'POST /drafts',
  'post-persona-context': 'POST /context',
  'post-persona-export': 'POST /export',
  'post-persona-generate': 'POST /generate',
  'post-persona-generations': 'POST /generations',
  'post-persona-group': 'POST /group',
  'post-persona-problem': 'POST /problem',
  'post-persona-refresh': 'POST /refresh',
  'get-persona-watch': 'GET /watch',
  'post-persona-watch': 'POST /watch',
  'post-persona-text-download': 'POST /text_download',
  'post-persona-call-download': 'POST /call_download',
  'post-persona-file-download': 'POST /file_download',
  'types': 'Types',
}
