export default {
  'post-rubrics-get': 'POST /get',
  'post-rubrics-search': 'POST /search',
  'post-rubrics-create': 'POST /create',
  'post-rubrics-update': 'POST /update',
  'post-rubrics-duplicate': 'POST /duplicate',
  'post-rubrics-delete': 'POST /delete',
  'patch-rubrics-draft': 'PATCH /draft',
  'post-rubrics-drafts': 'POST /drafts',
  'post-rubrics-docs': 'POST /docs',
  'post-rubrics-export': 'POST /export',
  'post-rubrics-csv': 'POST /csv',
  'post-rubrics-refresh': 'POST /refresh',
  'types': 'Types',
}
