export default {
  'post-agent-title': 'POST /title',
  'post-agent-context': 'POST /context',
  'post-agent-get': 'POST /get',
  'post-agent-search': 'POST /search',
  'post-agent-create': 'POST /create',
  'post-agent-csv': 'POST /csv',
  'post-agent-update': 'POST /update',
  'post-agent-duplicate': 'POST /duplicate',
  'post-agent-delete': 'POST /delete',
  'post-agent-draft': 'POST /draft',
  'post-agent-drafts': 'POST /drafts',
  'post-agent-export': 'POST /export',
  'post-agent-generate': 'POST /generate',
  'post-agent-generations': 'POST /generations',
  'post-agent-group': 'POST /group',
  'post-agent-problem': 'POST /problem',
  'post-agent-refresh': 'POST /refresh',
  'get-agent-watch': 'GET /watch',
  'post-agent-text-download': 'POST /text_download',
  'post-agent-file-download': 'POST /file_download',
  'post-agent-call-download': 'POST /call_download',
  'types': 'Types',
}
