export default {
  'post-agent-context': 'POST /context',
  'post-agent-get': 'POST /get',
  'post-agent-search': 'POST /search',
  'post-agent-create': 'POST /create',
  'post-agent-csv': 'POST /csv',
  'post-agent-update': 'POST /update',
  'post-agent-duplicate': 'POST /duplicate',
  'post-agent-delete': 'POST /delete',
  'patch-agent-draft': 'PATCH /draft',
  'post-agent-drafts': 'POST /drafts',
  'post-agent-export': 'POST /export',
  'post-agent-generate': 'POST /generate',
  'post-agent-generations': 'POST /generations',
  'post-agent-group': 'POST /group',
  'post-agent-problem': 'POST /problem',
  'post-agent-refresh': 'POST /refresh',
  'types': 'Types',
}
