export default {
  'client-config': 'glow auths client-config',
  'context': 'glow auths context',
  'create': 'glow auths create',
  'csv': 'glow auths csv',
  'delete': 'glow auths delete',
  'draft': 'glow auths draft',
  'drafts': 'glow auths drafts',
  'duplicate': 'glow auths duplicate',
  'export': 'glow auths export',
  'generate': 'glow auths generate',
  'generations': 'glow auths generations',
  'get': 'glow auths get',
  'group': 'glow auths group',
  'problem': 'glow auths problem',
  'refresh': 'glow auths refresh',
  'search': 'glow auths search',
  'title': 'glow auths title',
  'update': 'glow auths update',
  'watch': 'glow auths watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
