export default {
  'post-simulations-get': 'POST /get',
  'post-simulations-search': 'POST /search',
  'post-simulations-create': 'POST /create',
  'post-simulations-csv': 'POST /csv',
  'post-simulations-update': 'POST /update',
  'post-simulations-duplicate': 'POST /duplicate',
  'post-simulations-delete': 'POST /delete',
  'patch-simulations-draft': 'PATCH /draft',
  'post-simulations-drafts': 'POST /drafts',
  'post-simulations-export': 'POST /export',
  'post-simulations-docs': 'POST /docs',
  'post-simulations-refresh': 'POST /refresh',
  'types': 'Types',
}
