export default {
  'context': 'glow simulations context',
  'create': 'glow simulations create',
  'csv': 'glow simulations csv',
  'delete': 'glow simulations delete',
  'draft': 'glow simulations draft',
  'drafts': 'glow simulations drafts',
  'duplicate': 'glow simulations duplicate',
  'export': 'glow simulations export',
  'generate': 'glow simulations generate',
  'generations': 'glow simulations generations',
  'get': 'glow simulations get',
  'group': 'glow simulations group',
  'problem': 'glow simulations problem',
  'refresh': 'glow simulations refresh',
  'search': 'glow simulations search',
  'title': 'glow simulations title',
  'update': 'glow simulations update',
  'watch': 'glow simulations watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
