export default {
  'context': 'glow documents context',
  'create': 'glow documents create',
  'csv': 'glow documents csv',
  'delete': 'glow documents delete',
  'draft': 'glow documents draft',
  'drafts': 'glow documents drafts',
  'duplicate': 'glow documents duplicate',
  'export': 'glow documents export',
  'generate': 'glow documents generate',
  'generations': 'glow documents generations',
  'get': 'glow documents get',
  'group': 'glow documents group',
  'problem': 'glow documents problem',
  'refresh': 'glow documents refresh',
  'search': 'glow documents search',
  'title': 'glow documents title',
  'update': 'glow documents update',
  'watch': 'glow documents watch',
  'call': 'Call',
  'file': 'File',
  'image': 'Image',
  'text': 'Text',
}
