export default {
  index: 'Introduction',
  'start': 'Start',
  'how-it-works': 'How It Works',
  'tutorial': 'Design Your First Simulation',
  'patterns': 'Patterns & Best Practices',
  'annotated-example': 'Annotated Example',
  '---general': { type: 'separator', title: 'General' },
  'authentication': 'Authentication',
  'connect': 'Connect',
  'context': 'Context',
  'emulation': 'Emulation',
  'generate': 'Generate',
  'info': 'Info',
  'other': 'Other',
  'problem': 'Problem',
  'stream': 'Stream',
  '---experience': { type: 'separator', title: 'Experience' },
  'attempt': 'Attempt',
  'chat': 'Chat',
  'home': 'Home',
  'practice': 'Practice',
  '---testing': { type: 'separator', title: 'Testing' },
  'benchmark': 'Benchmark',
  'test': 'Test',
  'invocation': 'Invocation',
  '---training': { type: 'separator', title: 'Training' },
  'cohorts': 'Cohorts',
  'simulations': 'Simulations',
  'scenarios': 'Scenarios',
  'personas': 'Personas',
  '---analytics': { type: 'separator', title: 'Analytics' },
  'dashboard': 'Dashboard',
  'reports': 'Reports',
  'activity': 'Activity',
  'pricing': 'Pricing',
  'leaderboard': 'Leaderboard',
  '---intelligence': { type: 'separator', title: 'Intelligence' },
  'agents': 'Agents',
  'models': 'Models',
  'providers': 'Providers',
  'tools': 'Tools',
  '---management': { type: 'separator', title: 'Management' },
  'profiles': 'Profiles',
  'documents': 'Documents',
  'parameters': 'Parameters',
  'fields': 'Fields',
  '---system': { type: 'separator', title: 'System' },
  'departments': 'Departments',
  'rubrics': 'Rubrics',
  'auths': 'Auths',
  'evals': 'Evals',
  '---other-section': { type: 'separator', title: 'Other' },
  'health': 'Health',
  'settings': 'Settings',
  'record': 'Record',
  'group': 'Group',
  'session': 'Session',
  '---ref': { type: 'separator' },
  'api-reference': 'API Reference',
  'cli-reference': 'CLI Reference',
}
