export default {
  index: 'Introduction',
  start: 'Start',
  'how-it-works': 'How It Works',
  tutorial: 'Design Your First Simulation',
  patterns: 'Patterns & Best Practices',
  'annotated-example': 'Annotated Example',
  authentication: 'Authentication',
  settings: 'Settings',

  '---attempt': { type: 'separator', title: 'Attempt' },
  chat: 'Chat',
  home: 'Home',
  practice: 'Practice',
  dashboard: 'Dashboard',
  reports: 'Reports',
  leaderboard: 'Leaderboard',

  '---test': { type: 'separator', title: 'Test' },
  benchmark: 'Benchmark',
  invocation: 'Invocation',

  '---system': { type: 'separator', title: 'System' },
  activity: 'Activity',
  health: 'Health',
  pricing: 'Pricing',
  session: 'Session',
  group: 'Group',

  '---training': { type: 'separator', title: 'Training' },
  cohorts: 'Cohorts',
  personas: 'Personas',
  scenarios: 'Scenarios',
  simulations: 'Simulations',

  '---management': { type: 'separator', title: 'Management' },
  documents: 'Documents',
  fields: 'Fields',
  parameters: 'Parameters',
  profiles: 'Profiles',

  '---intelligence': { type: 'separator', title: 'Intelligence' },
  agents: 'Agents',
  models: 'Models',
  providers: 'Providers',
  tools: 'Tools',

  '---platform': { type: 'separator', title: 'Platform' },
  auths: 'Auths',
  departments: 'Departments',
  evals: 'Evals',
  rubrics: 'Rubrics',

  '---ref': { type: 'separator', title: 'Reference' },
  'api-reference': 'API Reference',
  'cli-reference': 'CLI Reference',
}
