// AUTO-GENERATED by scripts/gen-demo-manifest.mjs — do not edit by hand.
// Lists every per-topic demo video present in public/demos/.
// Regenerate via `node scripts/gen-demo-manifest.mjs` (or `make sync-types`).

export const DEMO_TOPICS: ReadonlySet<string> = new Set([

])
