export default {
  'post-profile-get': 'POST /get',
  'post-profile-search': 'POST /search',
  'post-profile-create': 'POST /create',
  'post-profile-update': 'POST /update',
  'post-profile-duplicate': 'POST /duplicate',
  'patch-profile-draft': 'PATCH /draft',
  'post-profile-drafts': 'POST /drafts',
  'post-profile-delete': 'POST /delete',
  'post-profile-export': 'POST /export',
  'post-profile-generate': 'POST /generate',
  'post-profile-generations': 'POST /generations',
  'post-profile-group': 'POST /group',
  'post-profile-problem': 'POST /problem',
  'post-profile-refresh': 'POST /refresh',
  'post-profile-context': 'POST /context',
  'post-profile-emulate': 'POST /emulate',
  'post-profile-unemulate': 'POST /unemulate',
  'types': 'Types',
}
