export default {
  'post-profile-title': 'POST /title',
  'post-profile-get': 'POST /get',
  'post-profile-search': 'POST /search',
  'post-profile-create': 'POST /create',
  'post-profile-csv': 'POST /csv',
  'post-profile-update': 'POST /update',
  'post-profile-duplicate': 'POST /duplicate',
  'post-profile-draft': 'POST /draft',
  'post-profile-drafts': 'POST /drafts',
  'post-profile-delete': 'POST /delete',
  'post-profile-export': 'POST /export',
  'post-profile-generate': 'POST /generate',
  'post-profile-generations': 'POST /generations',
  'post-profile-group': 'POST /group',
  'post-profile-problem': 'POST /problem',
  'post-profile-refresh': 'POST /refresh',
  'get-profile-watch': 'GET /watch',
  'post-profile-context': 'POST /context',
  'post-profile-emulate': 'POST /emulate',
  'post-profile-unemulate': 'POST /unemulate',
  'post-profile-text-download': 'POST /text_download',
  'post-profile-call-download': 'POST /call_download',
  'post-profile-file-download': 'POST /file_download',
  'types': 'Types',
}
