export default {
  'context': 'glow scenarios context',
  'create': 'glow scenarios create',
  'csv': 'glow scenarios csv',
  'delete': 'glow scenarios delete',
  'draft': 'glow scenarios draft',
  'drafts': 'glow scenarios drafts',
  'duplicate': 'glow scenarios duplicate',
  'export': 'glow scenarios export',
  'generate': 'glow scenarios generate',
  'generations': 'glow scenarios generations',
  'get': 'glow scenarios get',
  'group': 'glow scenarios group',
  'problem': 'glow scenarios problem',
  'refresh': 'glow scenarios refresh',
  'search': 'glow scenarios search',
  'title': 'glow scenarios title',
  'update': 'glow scenarios update',
  'watch': 'glow scenarios watch',
  'call': 'Call',
  'file': 'File',
  'image': 'Image',
  'text': 'Text',
  'video': 'Video',
}
