export default {
  'call_download': 'glow scenarios call_download',
  'context': 'glow scenarios context',
  'create': 'glow scenarios create',
  'csv': 'glow scenarios csv',
  'delete': 'glow scenarios delete',
  'draft': 'glow scenarios draft',
  'drafts': 'glow scenarios drafts',
  'duplicate': 'glow scenarios duplicate',
  'export': 'glow scenarios export',
  'file_download': 'glow scenarios file_download',
  'file_preview': 'glow scenarios file_preview',
  'generate': 'glow scenarios generate',
  'generations': 'glow scenarios generations',
  'get': 'glow scenarios get',
  'group': 'glow scenarios group',
  'image_download': 'glow scenarios image_download',
  'image_upload': 'glow scenarios image_upload',
  'problem': 'glow scenarios problem',
  'refresh': 'glow scenarios refresh',
  'search': 'glow scenarios search',
  'text_download': 'glow scenarios text_download',
  'title': 'glow scenarios title',
  'update': 'glow scenarios update',
  'video_download': 'glow scenarios video_download',
  'video_upload': 'glow scenarios video_upload',
  'watch': 'glow scenarios watch',
}
