export default {
  'context': 'glow rubrics context',
  'create': 'glow rubrics create',
  'csv': 'glow rubrics csv',
  'delete': 'glow rubrics delete',
  'draft': 'glow rubrics draft',
  'drafts': 'glow rubrics drafts',
  'duplicate': 'glow rubrics duplicate',
  'export': 'glow rubrics export',
  'generate': 'glow rubrics generate',
  'generations': 'glow rubrics generations',
  'get': 'glow rubrics get',
  'group': 'glow rubrics group',
  'problem': 'glow rubrics problem',
  'refresh': 'glow rubrics refresh',
  'search': 'glow rubrics search',
  'title': 'glow rubrics title',
  'update': 'glow rubrics update',
  'watch': 'glow rubrics watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
