export default {
  'call_download': 'glow tools call_download',
  'context': 'glow tools context',
  'create': 'glow tools create',
  'csv': 'glow tools csv',
  'delete': 'glow tools delete',
  'draft': 'glow tools draft',
  'drafts': 'glow tools drafts',
  'duplicate': 'glow tools duplicate',
  'export': 'glow tools export',
  'file_download': 'glow tools file_download',
  'generate': 'glow tools generate',
  'generations': 'glow tools generations',
  'get': 'glow tools get',
  'group': 'glow tools group',
  'preview': 'glow tools preview',
  'problem': 'glow tools problem',
  'refresh': 'glow tools refresh',
  'search': 'glow tools search',
  'text_download': 'glow tools text_download',
  'title': 'glow tools title',
  'update': 'glow tools update',
  'watch': 'glow tools watch',
}
