export default {
  'context': 'glow models context',
  'create': 'glow models create',
  'csv': 'glow models csv',
  'delete': 'glow models delete',
  'draft': 'glow models draft',
  'drafts': 'glow models drafts',
  'duplicate': 'glow models duplicate',
  'export': 'glow models export',
  'generate': 'glow models generate',
  'generations': 'glow models generations',
  'get': 'glow models get',
  'group': 'glow models group',
  'problem': 'glow models problem',
  'refresh': 'glow models refresh',
  'search': 'glow models search',
  'title': 'glow models title',
  'update': 'glow models update',
  'watch': 'glow models watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
