export default {
  'context': 'glow profiles context',
  'create': 'glow profiles create',
  'csv': 'glow profiles csv',
  'delete': 'glow profiles delete',
  'draft': 'glow profiles draft',
  'drafts': 'glow profiles drafts',
  'duplicate': 'glow profiles duplicate',
  'emulate': 'glow profiles emulate',
  'export': 'glow profiles export',
  'generate': 'glow profiles generate',
  'generations': 'glow profiles generations',
  'get': 'glow profiles get',
  'group': 'glow profiles group',
  'problem': 'glow profiles problem',
  'refresh': 'glow profiles refresh',
  'search': 'glow profiles search',
  'title': 'glow profiles title',
  'unemulate': 'glow profiles unemulate',
  'update': 'glow profiles update',
  'watch': 'glow profiles watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
