export default {
  'post-system-title': 'POST /title',
  'post-system-context': 'POST /context',
  'post-system-export': 'POST /export',
  'post-system-generate': 'POST /generate',
  'post-system-generations': 'POST /generations',
  'post-system-groups': 'POST /groups',
  'post-system-sessions': 'POST /sessions',
  'post-system-resolve': 'POST /resolve',
  'post-system-problem': 'POST /problem',
  'post-system-refresh': 'POST /refresh',
  'get-system-watch': 'GET /watch',
  'post-system-group': 'POST /group',
  'post-system-session': 'POST /session',
  'post-system-health': 'POST /health',
  'post-system-activity': 'POST /activity',
  'post-system-pricing': 'POST /pricing',
  'post-system-audio-download': 'POST /audio_download',
  'post-system-call-download': 'POST /call_download',
  'post-system-file-download': 'POST /file_download',
  'post-system-file-preview': 'POST /file_preview',
  'post-system-image-download': 'POST /image_download',
  'post-system-text-download': 'POST /text_download',
  'post-system-video-download': 'POST /video_download',
  'types': 'Types',
}
