export default {
  'post-provider-search': 'POST /search',
  'post-provider-get': 'POST /get',
  'post-provider-create': 'POST /create',
  'post-provider-update': 'POST /update',
  'post-provider-duplicate': 'POST /duplicate',
  'post-provider-delete': 'POST /delete',
  'patch-provider-draft': 'PATCH /draft',
  'post-provider-drafts': 'POST /drafts',
  'post-provider-context': 'POST /context',
  'post-provider-export': 'POST /export',
  'post-provider-csv': 'POST /csv',
  'post-provider-refresh': 'POST /refresh',
  'post-provider-decrypt': 'POST /decrypt',
  'post-provider-generate': 'POST /generate',
  'post-provider-generations': 'POST /generations',
  'post-provider-group': 'POST /group',
  'post-provider-problem': 'POST /problem',
  'types': 'Types',
}
