export default {
  'post-fields-get': 'POST /get',
  'post-fields-search': 'POST /search',
  'post-fields-create': 'POST /create',
  'post-fields-update': 'POST /update',
  'post-fields-duplicate': 'POST /duplicate',
  'post-fields-delete': 'POST /delete',
  'patch-fields-draft': 'PATCH /draft',
  'post-fields-drafts': 'POST /drafts',
  'post-fields-docs': 'POST /docs',
  'post-fields-export': 'POST /export',
  'post-fields-csv': 'POST /csv',
  'post-fields-refresh': 'POST /refresh',
  'types': 'Types',
}
