export default {
  'post-cohort-search': 'POST /search',
  'post-cohort-get': 'POST /get',
  'post-cohort-create': 'POST /create',
  'post-cohort-update': 'POST /update',
  'post-cohort-duplicate': 'POST /duplicate',
  'post-cohort-delete': 'POST /delete',
  'patch-cohort-draft': 'PATCH /draft',
  'post-cohort-drafts': 'POST /drafts',
  'post-cohort-export': 'POST /export',
  'post-cohort-csv': 'POST /csv',
  'post-cohort-context': 'POST /context',
  'post-cohort-generate': 'POST /generate',
  'post-cohort-generations': 'POST /generations',
  'post-cohort-group': 'POST /group',
  'post-cohort-problem': 'POST /problem',
  'post-cohort-refresh': 'POST /refresh',
  'types': 'Types',
}
