export default {
  'context': 'glow providers context',
  'create': 'glow providers create',
  'csv': 'glow providers csv',
  'decrypt': 'glow providers decrypt',
  'delete': 'glow providers delete',
  'draft': 'glow providers draft',
  'drafts': 'glow providers drafts',
  'duplicate': 'glow providers duplicate',
  'export': 'glow providers export',
  'generate': 'glow providers generate',
  'generations': 'glow providers generations',
  'get': 'glow providers get',
  'group': 'glow providers group',
  'problem': 'glow providers problem',
  'refresh': 'glow providers refresh',
  'search': 'glow providers search',
  'title': 'glow providers title',
  'update': 'glow providers update',
  'watch': 'glow providers watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
