export default {
  'post-tools-search': 'POST /search',
  'post-tools-get': 'POST /get',
  'post-tools-create': 'POST /create',
  'post-tools-update': 'POST /update',
  'post-tools-duplicate': 'POST /duplicate',
  'post-tools-delete': 'POST /delete',
  'patch-tools-draft': 'PATCH /draft',
  'post-tools-drafts': 'POST /drafts',
  'post-tools-export': 'POST /export',
  'post-tools-csv': 'POST /csv',
  'post-tools-docs': 'POST /docs',
  'post-tools-refresh': 'POST /refresh',
  'types': 'Types',
}
