#!/bin/bash
# Generate docker-compose.override.yml for docs deployment provisioning.
#
# Creates an external Docker network for API connectivity and generates
# Traefik labels for HTTPS routing + deployment network for app services.
#
# Usage:
#   ./scripts/provision.sh deploy --name <id> --instance-id <id> --subdomain <sub> --base-domain <domain> --compose-dir <dir> --entry-service <svc> --entry-port <port>
#   ./scripts/provision.sh teardown --name <name> --compose-dir <dir>

set -e

COMMAND="${1:?Usage: $0 <deploy|teardown> [options]}"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --instance-id) INSTANCE_ID="$2"; shift 2 ;;
    --api-domain) API_DOMAIN="$2"; shift 2 ;;
    --subdomain) SUBDOMAIN="$2"; shift 2 ;;
    --base-domain) BASE_DOMAIN="$2"; shift 2 ;;
    --compose-dir) COMPOSE_DIR="$2"; shift 2 ;;
    --entry-service) ENTRY_SERVICE="$2"; shift 2 ;;
    --entry-port) ENTRY_PORT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

case "$COMMAND" in
  deploy)
    : "${NAME:?--name required}"
    : "${INSTANCE_ID:?--instance-id required}"
    : "${COMPOSE_DIR:?--compose-dir required}"
    : "${SUBDOMAIN:?--subdomain required}"
    : "${BASE_DOMAIN:?--base-domain required}"
    : "${ENTRY_SERVICE:?--entry-service required}"
    : "${ENTRY_PORT:?--entry-port required}"

    DOMAIN="${SUBDOMAIN}.${BASE_DOMAIN}"
    DEPLOY_NETWORK="glow-${INSTANCE_ID}"

    # Ensure external networks exist (API creates the deployment network;
    # this is a no-op if it already exists)
    docker network create "$DEPLOY_NETWORK" 2>/dev/null || true
    docker network create traefik_routing 2>/dev/null || true

    cd "$COMPOSE_DIR"
    rm -f docker-compose.override.yml

    cat > "$COMPOSE_DIR/docker-compose.override.yml" <<OVERRIDE
# Auto-generated by provision.sh -- do not edit manually
services:
  ${ENTRY_SERVICE}:
    container_name: ${NAME}-nginx
    networks:
    - traefik_routing
    - deployment
    labels:
    - traefik.enable=true
    - traefik.http.routers.docs-${NAME}.rule=Host(\`${DOMAIN}\`)
    - traefik.http.routers.docs-${NAME}.entrypoints=websecure
    - traefik.http.routers.docs-${NAME}.tls.certresolver=letsencrypt
    - traefik.http.routers.docs-${NAME}.middlewares=secure-public@file
    - traefik.http.services.docs-${NAME}.loadbalancer.server.port=${ENTRY_PORT}
    - traefik.docker.network=traefik_routing
    security_opt:
    - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    extra_hosts:
    - ${DOMAIN}:host-gateway${API_DOMAIN:+
    - ${API_DOMAIN}:host-gateway}
  app-blue:
    networks:
      deployment:
        aliases:
        - docs
    extra_hosts:
    - ${DOMAIN}:host-gateway${API_DOMAIN:+
    - ${API_DOMAIN}:host-gateway}
  app-green:
    networks:
      deployment:
        aliases:
        - docs
    extra_hosts:
    - ${DOMAIN}:host-gateway${API_DOMAIN:+
    - ${API_DOMAIN}:host-gateway}
  docker-gen:
    container_name: ${NAME}-docker-gen
networks:
  traefik_routing:
    external: true
    name: traefik_routing
  deployment:
    external: true
    name: ${DEPLOY_NETWORK}
OVERRIDE
    echo "Traefik override generated for ${DOMAIN} -> ${ENTRY_SERVICE}:${ENTRY_PORT} (network: ${DEPLOY_NETWORK})"
    ;;

  teardown)
    : "${NAME:?--name required}"
    : "${COMPOSE_DIR:?--compose-dir required}"

    cd "$COMPOSE_DIR"
    docker compose down -v --remove-orphans 2>/dev/null || true
    rm -f docker-compose.override.yml

    echo "Teardown complete for $NAME"
    ;;

  *)
    echo "Unknown command: $COMMAND (use deploy or teardown)"
    exit 1
    ;;
esac
