#!/bin/bash
# Generate docker-compose.override.yml with Traefik routing labels.
#
# Usage:
#   ./scripts/provision.sh deploy --name <name> --subdomain <sub> --base-domain <domain> --compose-dir <dir> --entry-service <svc> --entry-port <port>
#   ./scripts/provision.sh teardown --name <name> --compose-dir <dir>

set -e

COMMAND="${1:?Usage: $0 <deploy|teardown> [options]}"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --subdomain) SUBDOMAIN="$2"; shift 2 ;;
    --base-domain) BASE_DOMAIN="$2"; shift 2 ;;
    --compose-dir) COMPOSE_DIR="$2"; shift 2 ;;
    --entry-service) ENTRY_SERVICE="$2"; shift 2 ;;
    --entry-port) ENTRY_PORT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

case "$COMMAND" in
  deploy)
    : "${NAME:?--name required}"
    : "${SUBDOMAIN:?--subdomain required}"
    : "${BASE_DOMAIN:?--base-domain required}"
    : "${COMPOSE_DIR:?--compose-dir required}"
    : "${ENTRY_SERVICE:?--entry-service required}"
    : "${ENTRY_PORT:?--entry-port required}"

    DOMAIN="${SUBDOMAIN}.${BASE_DOMAIN}"
    docker network create traefik_routing 2>/dev/null || true

    cd "$COMPOSE_DIR"
    SERVICES=$(docker compose config --services 2>/dev/null || echo "$ENTRY_SERVICE")

    EXTRA_HOSTS=""
    for svc in $SERVICES; do
      [ "$svc" = "$ENTRY_SERVICE" ] && continue
      EXTRA_HOSTS="${EXTRA_HOSTS}
  ${svc}:
    extra_hosts:
    - ${DOMAIN}:host-gateway"
    done

    cat > "$COMPOSE_DIR/docker-compose.override.yml" <<OVERRIDE
# Auto-generated by provision.sh -- do not edit manually
services:
  ${ENTRY_SERVICE}:
    networks:
    - default
    - traefik_routing
    labels:
    - traefik.enable=true
    - traefik.http.routers.${NAME}.rule=Host(\`${DOMAIN}\`)
    - traefik.http.routers.${NAME}.entrypoints=websecure
    - traefik.http.routers.${NAME}.tls.certresolver=letsencrypt
    - traefik.http.routers.${NAME}.middlewares=secure-public@file
    - traefik.http.services.${NAME}.loadbalancer.server.port=${ENTRY_PORT}
    - traefik.docker.network=traefik_routing
    security_opt:
    - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    extra_hosts:
    - ${DOMAIN}:host-gateway${EXTRA_HOSTS}
networks:
  traefik_routing:
    external: true
    name: traefik_routing
OVERRIDE

    echo "Traefik override generated for ${DOMAIN} → ${ENTRY_SERVICE}:${ENTRY_PORT}"
    ;;

  teardown)
    : "${NAME:?--name required}"
    : "${COMPOSE_DIR:?--compose-dir required}"

    cd "$COMPOSE_DIR"
    docker compose down -v --remove-orphans 2>/dev/null || true
    rm -f docker-compose.override.yml
    echo "Teardown complete for $NAME"
    ;;

  *)
    echo "Unknown command: $COMMAND (use deploy or teardown)"
    exit 1
    ;;
esac
