export default {
  'post-parameter-get': 'POST /get',
  'post-parameter-search': 'POST /search',
  'post-parameter-create': 'POST /create',
  'post-parameter-update': 'POST /update',
  'post-parameter-duplicate': 'POST /duplicate',
  'post-parameter-context': 'POST /context',
  'post-parameter-delete': 'POST /delete',
  'patch-parameter-draft': 'PATCH /draft',
  'post-parameter-drafts': 'POST /drafts',
  'post-parameter-export': 'POST /export',
  'post-parameter-csv': 'POST /csv',
  'post-parameter-generate': 'POST /generate',
  'post-parameter-generations': 'POST /generations',
  'post-parameter-group': 'POST /group',
  'post-parameter-problem': 'POST /problem',
  'post-parameter-refresh': 'POST /refresh',
  'types': 'Types',
}
