export default {
  'post-parameter-title': 'POST /title',
  'post-parameter-get': 'POST /get',
  'post-parameter-search': 'POST /search',
  'post-parameter-create': 'POST /create',
  'post-parameter-update': 'POST /update',
  'post-parameter-duplicate': 'POST /duplicate',
  'post-parameter-context': 'POST /context',
  'post-parameter-delete': 'POST /delete',
  'post-parameter-draft': 'POST /draft',
  'post-parameter-drafts': 'POST /drafts',
  'post-parameter-export': 'POST /export',
  'post-parameter-csv': 'POST /csv',
  'post-parameter-generate': 'POST /generate',
  'post-parameter-generations': 'POST /generations',
  'post-parameter-group': 'POST /group',
  'post-parameter-problem': 'POST /problem',
  'post-parameter-refresh': 'POST /refresh',
  'get-parameter-watch': 'GET /watch',
  'post-parameter-text-download': 'POST /text_download',
  'post-parameter-file-download': 'POST /file_download',
  'post-parameter-call-download': 'POST /call_download',
  'types': 'Types',
}
