export default {
  'post-auth-title': 'POST /title',
  'post-auth-context': 'POST /context',
  'post-auth-get': 'POST /get',
  'post-auth-search': 'POST /search',
  'post-auth-create': 'POST /create',
  'post-auth-csv': 'POST /csv',
  'post-auth-update': 'POST /update',
  'post-auth-duplicate': 'POST /duplicate',
  'post-auth-delete': 'POST /delete',
  'post-auth-draft': 'POST /draft',
  'post-auth-drafts': 'POST /drafts',
  'post-auth-export': 'POST /export',
  'post-auth-generate': 'POST /generate',
  'post-auth-generations': 'POST /generations',
  'post-auth-group': 'POST /group',
  'post-auth-problem': 'POST /problem',
  'post-auth-refresh': 'POST /refresh',
  'get-auth-watch': 'GET /watch',
  'post-auth-watch': 'POST /watch',
  'post-auth-text-download': 'POST /text_download',
  'post-auth-call-download': 'POST /call_download',
  'post-auth-file-download': 'POST /file_download',
  'types': 'Types',
}
