export default {
  'context': 'glow personas context',
  'create': 'glow personas create',
  'csv': 'glow personas csv',
  'delete': 'glow personas delete',
  'draft': 'glow personas draft',
  'drafts': 'glow personas drafts',
  'duplicate': 'glow personas duplicate',
  'export': 'glow personas export',
  'generate': 'glow personas generate',
  'generations': 'glow personas generations',
  'get': 'glow personas get',
  'group': 'glow personas group',
  'problem': 'glow personas problem',
  'refresh': 'glow personas refresh',
  'search': 'glow personas search',
  'title': 'glow personas title',
  'update': 'glow personas update',
  'watch': 'glow personas watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
