export default {
  'post-personas-get': 'POST /get',
  'post-personas-search': 'POST /search',
  'post-personas-create': 'POST /create',
  'post-personas-csv': 'POST /csv',
  'post-personas-update': 'POST /update',
  'post-personas-duplicate': 'POST /duplicate',
  'post-personas-delete': 'POST /delete',
  'patch-personas-draft': 'PATCH /draft',
  'post-personas-drafts': 'POST /drafts',
  'post-personas-docs': 'POST /docs',
  'post-personas-export': 'POST /export',
  'post-personas-refresh': 'POST /refresh',
  'types': 'Types',
}
