export default {
  'post-providers-search': 'POST /search',
  'post-providers-get': 'POST /get',
  'post-providers-create': 'POST /create',
  'post-providers-update': 'POST /update',
  'post-providers-duplicate': 'POST /duplicate',
  'post-providers-delete': 'POST /delete',
  'patch-providers-draft': 'PATCH /draft',
  'post-providers-drafts': 'POST /drafts',
  'post-providers-docs': 'POST /docs',
  'post-providers-export': 'POST /export',
  'post-providers-csv': 'POST /csv',
  'post-providers-refresh': 'POST /refresh',
  'post-providers-decrypt': 'POST /decrypt',
  'types': 'Types',
}
