export default {
  'get-well-known-oauth-authorization-server': 'GET /.well-known/oauth-authorization-server',
  'get-jwks': 'GET /jwks',
  'get-well-known-openid-configuration': 'GET /.well-known/openid-configuration',
  'get-authorize': 'GET /authorize',
  'get-oidc-callback': 'GET /oidc-callback',
  'post-token': 'POST /token',
  'get-userinfo': 'GET /userinfo',
  'get-login': 'GET /login',
  'get-callback': 'GET /callback',
  'get-logout': 'GET /logout',
  'get-me': 'GET /me',
  'get-auth-client-config': 'GET /auth/client-config',
  'get': 'GET /',
}
