export default {
  'context': 'glow cohorts context',
  'create': 'glow cohorts create',
  'csv': 'glow cohorts csv',
  'delete': 'glow cohorts delete',
  'draft': 'glow cohorts draft',
  'drafts': 'glow cohorts drafts',
  'duplicate': 'glow cohorts duplicate',
  'export': 'glow cohorts export',
  'generate': 'glow cohorts generate',
  'generations': 'glow cohorts generations',
  'get': 'glow cohorts get',
  'group': 'glow cohorts group',
  'problem': 'glow cohorts problem',
  'refresh': 'glow cohorts refresh',
  'search': 'glow cohorts search',
  'title': 'glow cohorts title',
  'update': 'glow cohorts update',
  'watch': 'glow cohorts watch',
  'call': 'Call',
  'file': 'File',
  'text': 'Text',
}
