export default {
  'post-parameters-get': 'POST /get',
  'post-parameters-search': 'POST /search',
  'post-parameters-create': 'POST /create',
  'post-parameters-update': 'POST /update',
  'post-parameters-duplicate': 'POST /duplicate',
  'post-parameters-delete': 'POST /delete',
  'patch-parameters-draft': 'PATCH /draft',
  'post-parameters-drafts': 'POST /drafts',
  'post-parameters-docs': 'POST /docs',
  'post-parameters-export': 'POST /export',
  'post-parameters-csv': 'POST /csv',
  'post-parameters-refresh': 'POST /refresh',
  'types': 'Types',
}
