export default {
  'post-rubric-get': 'POST /get',
  'post-rubric-search': 'POST /search',
  'post-rubric-context': 'POST /context',
  'post-rubric-create': 'POST /create',
  'post-rubric-update': 'POST /update',
  'post-rubric-duplicate': 'POST /duplicate',
  'post-rubric-delete': 'POST /delete',
  'patch-rubric-draft': 'PATCH /draft',
  'post-rubric-drafts': 'POST /drafts',
  'post-rubric-export': 'POST /export',
  'post-rubric-csv': 'POST /csv',
  'post-rubric-generate': 'POST /generate',
  'post-rubric-generations': 'POST /generations',
  'post-rubric-group': 'POST /group',
  'post-rubric-problem': 'POST /problem',
  'post-rubric-refresh': 'POST /refresh',
  'types': 'Types',
}
