export default {
  'archive': 'glow tests archive',
  'complete': 'glow tests complete',
  'context': 'glow tests context',
  'draft': 'glow tests draft',
  'drafts': 'glow tests drafts',
  'export': 'glow tests export',
  'feedback': 'glow tests feedback',
  'generate': 'glow tests generate',
  'generations': 'glow tests generations',
  'get': 'glow tests get',
  'grade': 'glow tests grade',
  'group': 'glow tests group',
  'problem': 'glow tests problem',
  'refresh': 'glow tests refresh',
  'search': 'glow tests search',
  'start': 'glow tests start',
  'stop': 'glow tests stop',
  'title': 'glow tests title',
  'watch': 'glow tests watch',
  'benchmark': 'Benchmark',
  'invocation': 'Invocation',
}
