export default {
  'call_download': 'glow departments call_download',
  'context': 'glow departments context',
  'create': 'glow departments create',
  'csv': 'glow departments csv',
  'delete': 'glow departments delete',
  'draft': 'glow departments draft',
  'drafts': 'glow departments drafts',
  'duplicate': 'glow departments duplicate',
  'export': 'glow departments export',
  'file_download': 'glow departments file_download',
  'generate': 'glow departments generate',
  'generations': 'glow departments generations',
  'get': 'glow departments get',
  'group': 'glow departments group',
  'problem': 'glow departments problem',
  'refresh': 'glow departments refresh',
  'search': 'glow departments search',
  'text_download': 'glow departments text_download',
  'title': 'glow departments title',
  'update': 'glow departments update',
  'watch': 'glow departments watch',
}
